# =============================================================================
# Bridge Stack - Biboumi, Matterbridge
# =============================================================================
# TODO: Not yet deployed. See apps/bridge/README.md for implementation plan.
# When ready, uncomment services and wire into root compose.
# =============================================================================

name: atl-bridge

include:
  - networks.yaml

services: {}
# Placeholder - bridge services to be added when implemented
