# =============================================================================
# Cert Manager - Lego for Let's Encrypt
# =============================================================================
# Paths relative to this file's directory (infra/compose/)
# Scripts in scripts/cert-manager/
# =============================================================================

name: atl-cert-manager

include:
  - networks.yaml

services:
  cert-manager:
    image: goacme/lego:latest
    container_name: atl-cert-manager
    hostname: atl-cert-manager
    restart: unless-stopped
    entrypoint: /scripts/run.sh

    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - IRC_ROOT_DOMAIN=${IRC_ROOT_DOMAIN:-atl.chat}
      - SSL_DOMAIN=${SSL_DOMAIN:-}

    volumes:
      - ../../data/certs:/data
      - ../../scripts/cert-manager:/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - atl-chat
