# =============================================================================
# Cert Manager - Lego for Let's Encrypt
# =============================================================================
# Paths relative to this file's directory (infra/compose/)
# Scripts in scripts/cert-manager/
# =============================================================================

name: atl-cert-manager

include:
  - networks.yaml

services:
  cert-manager:
    image: goacme/lego:v4.32.0
    container_name: atl-cert-manager
    hostname: atl-cert-manager
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    entrypoint: /scripts/run.sh

    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - IRC_ROOT_DOMAIN=${IRC_ROOT_DOMAIN:-atl.chat}
      - SSL_DOMAIN=${SSL_DOMAIN:-}

    logging:
      driver: json-file
      options:
        max-size: "${LOG_MAX_SIZE:-50m}"
        max-file: "${LOG_MAX_FILES:-5}"
        compress: "true"

    volumes:
      - ../../data/certs:/data
      - ../../scripts/cert-manager:/scripts:ro

    networks:
      - atl-chat
