# =============================================================================
# IRC Stack - UnrealIRCd, Atheme, WebPanel
# =============================================================================
# Paths are relative to this file's directory (infra/compose/)
# =============================================================================

name: atl-irc

include:
  - networks.yaml

services:
  # ============================================================================
  # UNREALIRCD - Main IRC Server
  # ============================================================================
  atl-irc-server:
    build:
      context: ../../apps/unrealircd
      dockerfile: Containerfile
      args:
        UNREALIRCD_VERSION: ${UNREALIRCD_VERSION:-6.2.0.1}
        UID: ${PUID:-1000}
        GID: ${PGID:-1000}

    container_name: atl-irc-server
    hostname: atl-irc-server
    init: true
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

    volumes:
      - ../../apps/unrealircd/config:/home/unrealircd/unrealircd/config
      - ../../data/irc/data:/home/unrealircd/unrealircd/data
      - ../../data/irc/logs:/home/unrealircd/unrealircd/logs
      - ../../data/certs:/home/unrealircd/unrealircd/certs:ro

    env_file:
      - path: ../../.env
        required: false
      - path: ../../.env.dev
        required: false

    environment:
      - IRC_DOMAIN=${IRC_DOMAIN}
      - IRC_SSL_CERT_PATH=${IRC_SSL_CERT_PATH:-/home/unrealircd/unrealircd/certs/live/${IRC_DOMAIN:-irc.localhost}/fullchain.pem}
      - IRC_SSL_KEY_PATH=${IRC_SSL_KEY_PATH:-/home/unrealircd/unrealircd/certs/live/${IRC_DOMAIN:-irc.localhost}/privkey.pem}
      - ATL_GATEWAY_IP=${ATL_GATEWAY_IP}
      - TZ=UTC
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}

    ports:
      - '${ATL_CHAT_IP:-127.0.0.1}:${IRC_TLS_PORT:-6697}:6697'
      - '${ATL_CHAT_IP:-127.0.0.1}:${IRC_SERVER_PORT:-6900}:6900'
      - '${ATL_CHAT_IP:-127.0.0.1}:${IRC_RPC_PORT:-8600}:8600'
      - '${ATL_CHAT_IP:-127.0.0.1}:${IRC_WEBSOCKET_PORT:-8000}:8000'
      - '${ATL_CHAT_IP:-127.0.0.1}:${ATHEME_HTTPD_PORT:-8081}:8081'

    networks:
      - atl-chat

    healthcheck:
      test: ['CMD', 'sh', '-c', 'echo ''{"jsonrpc":"2.0","method":"rpc.info","params":{},"id":1}'' | nc -U /home/unrealircd/unrealircd/data/rpc.socket 2>/dev/null | grep -q "\"result\""']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # ============================================================================
  # ATHEME - IRC Services
  # ============================================================================
  atl-irc-services:
    build:
      context: ../../apps/atheme
      dockerfile: Containerfile
      args:
        ATHEME_VERSION: ${ATHEME_VERSION:-master}
        UID: ${PUID:-1000}
        GID: ${PGID:-1000}

    container_name: atl-irc-services
    restart: unless-stopped

    depends_on:
      atl-irc-server:
        condition: service_healthy

    network_mode: service:atl-irc-server

    volumes:
      - ../../apps/atheme/config:/usr/local/atheme/etc
      - ../../data/atheme/data:/usr/local/atheme/data
      - ../../data/atheme/logs:/usr/local/atheme/logs

    environment:
      - TZ=UTC
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}

    healthcheck:
      test: [ 'CMD', 'pgrep', '-f', 'atheme-services' ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # ============================================================================
  # UNREALIRCD WEBPANEL
  # ============================================================================
  atl-irc-webpanel:
    build:
      context: ../../apps/webpanel
      dockerfile: Containerfile

    container_name: atl-irc-webpanel
    hostname: atl-irc-webpanel
    restart: unless-stopped

    depends_on:
      atl-irc-server:
        condition: service_healthy

    volumes:
      - ../../data/irc/webpanel-data:/var/www/html/unrealircd-webpanel/data

    env_file:
      - path: ../../.env
        required: false
      - path: ../../.env.dev
        required: false

    environment:
      - TZ=UTC

    ports:
      - '${WEBPANEL_PORT:-8080}:8080'

    networks:
      - atl-chat

  # TODO: Gamja (IRC web client) - see apps/gamja/
  # Containerfile exists but needs final stage + config. Wire when ready.
